metaDB:
  dbName: "api_gen_meta"
  dbType: "mysql"
  host: "localhost"
  port: 3306
  user: ""
  password: ""
dataDB:
  dbName: "api_gen_data"
  dbType: "mysql"
  host: "localhost"
  port: 3306
  user: ""
  password: ""
server:
  env: "development"
  host: "localhost"
  port: 3300
  maxUseCPU: 4
grpc:
  